name: CI

on: 
  issues:
    types: [opened]
  
jobs:
  notify_the_dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Send a message to the dashboard 
        run: curl https://2e339b92.ngrok.io/issues