name: CI

on: 
  issues:
    types: [opened, reopened]
  
jobs:
  notify_the_dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Send a message to the dashboard 
        run: curl https://github-issue-dashboard.herokuapp.com/issues