name: CI

on: 
  issues:
    types: [opened]
  

jobs:
  notify_the_dashboard:
    runs-on: ubuntu-latest
    steps:
      - name: Send a message to the dashboard 
        run: curl https://2e339b92.ngrok.io/issues
   
#   build:

#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v1
#     - name: Run a one-line script
#       run: echo Hello, world!
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
